project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"
    - "!R/"
    - "!partials/"
  resources:
    - "/assets/js/fullscreen-fig.js"

website:
  title: "CSPS Explorer"
  announcement:
    icon: exclamation-diamond-fill
    dismissable: false
    content: This website is a prototype, things might be incomplete, subject to change or not work/display as expected.
    type: warning
    position: above-navbar
  navbar:
    title: "Civil Service People Survey Explorer"
    logo: "assets/images/user-data-teal.svg"
    right:
      - text: Results
        menu: 
          - text: Introduction
            href: results/index.qmd
          - text: "---"
          - text: Civil Service results
          - text: Civil Service Benchmark 2024
            href: benchmark_results/index.qmd
          - text: All respondents 2024
            href: benchmark_results/all_respondents/index.qmd
          - text: "---"
          - text: Organisation results
          - text: Organisation summary
            href: organisation_results/index.qmd
          - text: Individual organisations
            href: organisation_results/2024/index.qmd
          - text: "---"
          - text: Demographics
          - text: "--"
          - text: Interactive
      - text: Insights
        href: insights/index.qmd
      - text: "About"
        href: about/index.qmd
  bread-crumbs: false
  favicon: "assets/images/user-data-teal-bg.png"
  page-footer:
    left:
      - text: "Civil Service People Survey Explorer"
        href: index.qmd
      - text: "&copy; Matt Kerlogue 2026, licensed under CC-BY-4.0"
        href: "about/legal.qmd#copyright"
    center:
      - text: "Contact"
        href: "about/contact.qmd"
      - text: "Source data"
        href: "results/source_data.qmd"
      - text: "Github"
        href: "https://www.github.com/mattkerlogue/csps-explorer"
    right:
      - text: "About this site"
        href: about/index.qmd
      - text: "Accessibility"
        href: "about/accessibility.qmd"
      - text: "Privacy"
        href: "about/privacy.qmd"
      - text: "Legal"
        href: "about/legal.qmd#disclaimer"

bibliography: bib.yml

format:
  html:
    title-block-banner: true
    theme:
      - custom.scss
    css: 
      - styles.css
    toc: true
    toc-location: left
    fig-cap-location: top
    tbl-cap-location: top
    link-external-icon: true
    email-obfuscation: javascript
    include-in-header:
      - text: <script src="/assets/js/fullscreen-fig.js"></script>

extensions:
  iconify:
    set: "carbon"
    flip: "horizontal"
    rotate: "90deg"
    inline: true
    mode: "svg"
