project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"
    - "!R/"
    - "!partials/"

website:
  title: "CSPS Explorer"
  navbar:
    title: "Civil Service People Survey Explorer"
    right:
      - text: Results
        menu: 
          - text: Introduction
            href: results/index.qmd
          - text: "---"
          - text: Civil Service results
          - text: Civil Service Benchmark 2024
            href: benchmark_results/index.qmd
          - text: All respondents 2024
            href: benchmark_results/all_respondents/index.qmd
          - text: "---"
          - text: Organisation results
          - text: Organisation summary
            href: organisation_results/index.qmd
          - text: Individual organisations
            href: organisation_results/2024/index.qmd
          - text: "---"
          - text: Demographics
          - text: "--"
          - text: Interactive
      - text: Insights
        href: insights/index.qmd
      - text: "About"
        href: about.qmd
  bread-crumbs: false
  back-to-top-navigation: true

bibliography: bib.yml

format:
  html:
    title-block-banner: true
    theme:
      - custom.scss
    css: 
      - styles.css
    toc: true
    toc-location: left
    fig-cap-location: top
    tbl-cap-location: top
    link-external-icon: true

extensions:
  iconify:
    set: "carbon"
    flip: "horizontal"
    rotate: "90deg"
    inline: true
    mode: "svg"
